# -*- coding: utf-8 -*-
"""EasyOCR_torch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141i0UGbMpHWjSc7c8BT09IHV60Csldgl
"""

!pip install torch ,torchvision 
!pip install easyocr

'''

https://www.youtube.com/watch?v=ZVKaWPW9oQY
`easyocr + torch `
Steps:
1. setting up and installing EasyOCR 
2. Extracting text from images 
3. Displaying results using Opencv

'''

import easyocr 
import cv2 
import matplotlib.pyplot as plt 
import numpy as np

"""# Read images and videos"""

path = 'stop.jpeg'

reader = easyocr.Reader(['en'],gpu=False)
result = reader.readtext(path)
result

"""# Draw results
> 单张图片
"""

top_left = tuple(result[0][0][0])
bottom_right = tuple(result[0][0][2])

text = result[0][1]
score = result[0][2]
font = cv2.FONT_HERSHEY_SIMPLEX

img = cv2.imread(path)
img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),5)
img = cv2.putText(img,text,top_left,font,1,(255,0,255),2,cv2.LINE_AA)
img = cv2.putText(img,str(score),bottom_right,font,0.5,(255,0,255),2,cv2.LINE_AA)

plt.imshow(img)
plt.show()

"""> 多张文件内容在同一个图片中，循环获得输出内容

"""

img = cv2.imread(path)
font = cv2.FONT_HERSHEY_SIMPLEX
for detection in result: 
  top_left = tuple([int(val) for val in detection[0][0]])
  bottom_right = tuple([int(val) for val in detection[0][2]])
  text = detection[1]
  score = detection[2]
  img = cv2.rectangle(img,top_left,bottom_right,(0,255,0),5)
  img = cv2.putText(img,text,top_left,font,1,(255,0,255),2,cv2.LINE_AA)
plt.imshow(img)
plt.show()

